#!/usr/local/bin/bash

VERSION=`uname -v | cut -d " " -f 2-9`

MINS=`/usr/bin/uptime | awk '{print $5}' | cut -d: -f2 | tr -d ,`
HRS=`/usr/bin/uptime | awk '{print $5}' | cut -d: -f1`
DAYS=`/usr/bin/uptime | awk '{print $3}'`
UPTIME="$DAYS Days, $HRS Hours and $MINS Minutes"

printf "\033[31;1m                                                 ,        , \033[m\n";
printf "\033[31;1m                                                /(        )\` \033[m\n";
printf "\033[1;32m    FFFFFFF \033[31;1m                                    \ \___   / | \033[m\n";
printf "\033[1;32m    FF \033[31;1m                                         /- _  \`-/  \' \033[m\n";
printf "\033[1;32m    FF \033[31;1m                                        (/\/ \ \   /\ \033[m\n";
printf "\033[1;32m    FFFFF RR RRR  EEEEE   EEEEE \033[31;1m               / /   | \`    \ \033[m\n";
printf "\033[1;32m    FF    RRR    EE   EE EE   EE \033[31;1m              O O   ) /    | \033[m\n";
printf "\033[1;32m    FF    RR     EEEEEEE EEEEEEE \033[31;1m              \`-^--\'\`<    \' \033[m\n";
printf "\033[1;32m    FF    RR     EE      EE \033[31;1m                 (_.)  _  )   / \033[m\n";
printf "\033[1;32m    FF    RR      EEEEEE  EEEEEE \033[31;1m             \`.___/\`   / \033[m\n";
printf "\033[31;1m                                                \`-----/ \033[m\n";
printf "\033[1;32m    BBBBBB     SSSSS    DDDDDD \033[31;1m    <----.     __ / __   \ \033[m\n";
printf "\033[1;32m    BB   BB   SS   SS   DD   DD \033[31;1m   <----|====O)))==) \) /==== \033[m\n";
printf "\033[1;32m    BB   BB   SS        DD   DD \033[31;1m   <----\'    \`--\' \`.__,\' \ \033[m\n";
printf "\033[1;32m    BBBBBB     SSSSS    DD   DD \033[31;1m                |        | \033[m\n";
printf "\033[1;32m    BB   BB        SS   DD   DD \033[31;1m                 \       / \033[m\n";
printf "\033[1;32m    BB   BB   SS   SS   DD   DD \033[31;1m           ______( (_  / \______ \033[m\n";
printf "\033[1;32m    BBBBBB     SSSSS    DDDDDD \033[31;1m          ,\'  ,-----\'   |        \ \033[m\n";
printf "\033[31;1m                                         \`--{__________)        \/ \033[m\n\n";
printf "\033[1;33m    $VERSION\033[m\n\n"
printf "\033[1;32m    Uptime:\033[m $UPTIME\n\n"
